# Generated by Django 2.0.13 on 2019-04-28 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('data', models.DateTimeField()),
                ('booleanConcluido', models.BooleanField(default=False)),
                ('local', models.TextField()),
                ('endereco', models.TextField()),
                ('cidade', models.TextField()),
                ('estado', models.TextField()),
                ('observacoes', models.TextField()),
                ('dataDeCadastro', models.DateTimeField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
