# Generated by Django 2.0.13 on 2019-04-29 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_auto_20190428_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaixaGeral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDoacaoDoacao', models.BooleanField(default=True)),
                ('tipoDoacaoRecebimento', models.BooleanField(default=False)),
                ('valor', models.CharField(max_length=20)),
                ('observacoes', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDoacaoDoacao', models.BooleanField(default=True)),
                ('tipoDoacaoRecebimento', models.BooleanField(default=False)),
                ('data', models.DateTimeField()),
                ('valor', models.CharField(max_length=20)),
                ('observacoes', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoCadastroPessoaFisica', models.BooleanField(default=True)),
                ('tipoCadastroPessoaJuridica', models.BooleanField(default=False)),
                ('tipoPessoaDoador', models.BooleanField(default=True)),
                ('tipoPessoaRecebedor', models.BooleanField(default=False)),
                ('nome', models.CharField(max_length=50)),
                ('cpfCnpj', models.CharField(max_length=14)),
                ('endereco', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=60)),
                ('estado', models.CharField(max_length=20)),
                ('telefone1', models.CharField(max_length=14)),
                ('telefone2', models.CharField(max_length=14)),
                ('observacoes', models.TextField()),
                ('dataDeCadastro', models.DateTimeField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='autor',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='booleanConcluido',
            new_name='concluido',
        ),
        migrations.AlterField(
            model_name='evento',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evento',
            name='cidade',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='evento',
            name='endereco',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='evento',
            name='estado',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='evento',
            name='local',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='doacao',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Pessoa'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='doacoes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Doacao'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Evento'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Pessoa'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='transacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.CaixaGeral'),
        ),
        migrations.AddField(
            model_name='caixageral',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Pessoa'),
        ),
    ]
